const PROFILE_STORAGE_KEY = 'userProfile';
const ADDRESS_STORAGE_KEY = 'userAddress';
const SERVICES_STORAGE_KEY = 'services';

export { PROFILE_STORAGE_KEY, ADDRESS_STORAGE_KEY, SERVICES_STORAGE_KEY };
