const EXPERIENCE_STORAGE_KEY = 'userExperience';
const PROFILE_STORAGE_KEY = 'userProfile';
const ADDRESS_STORAGE_KEY = 'userAddress';
const SERVICES_STORAGE_KEY = 'services';

export {
    EXPERIENCE_STORAGE_KEY,
    PROFILE_STORAGE_KEY,
    ADDRESS_STORAGE_KEY,
    SERVICES_STORAGE_KEY,
};
